// Generated by @starter/navigation from packages/features/src/app.feature.ts.
// Do not edit this file directly.
import { WebFeatureRenderer } from "@starter/ui-web";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Paramètres",
  description: "Paramètres du compte et préférences de l'application.",
  alternates: { canonical: "/parametres" },
  robots: { index: false, follow: false },
  openGraph: {
    title: "Paramètres",
    description: "Paramètres du compte et préférences de l'application.",
    type: "website",
    url: "/parametres",
  },
  twitter: {
    card: "summary",
    title: "Paramètres",
    description: "Paramètres du compte et préférences de l'application.",
  },
};

export default function Page() {
  return <WebFeatureRenderer featureId="settings" pageId="index" />;
}
