// Generated by @starter/navigation from packages/features/routes.config.json.
// Do not edit this file directly.
import { WebFeatureRenderer } from "@starter/ui-web";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Paramètres",
  description: "Préférences locales de démonstration.",
  alternates: { canonical: "/parametres" },
  robots: { index: false, follow: false },
  openGraph: {
    title: "Paramètres",
    description: "Préférences locales de démonstration.",
    type: "website",
    url: "/parametres",
  },
  twitter: {
    card: "summary",
    title: "Paramètres",
    description: "Préférences locales de démonstration.",
  },
};

export default function Page() {
  return <WebFeatureRenderer featureId="settings" />;
}
