// Generated by @starter/navigation from packages/features/src/app.feature.ts.
// Do not edit this file directly.
import { WebFeatureRenderer } from "@starter/ui-web";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Orders",
  description: "Liste et suivi des commandes.",
  alternates: { canonical: "/orders" },
  robots: { index: false, follow: false },
  openGraph: {
    title: "Orders",
    description: "Liste et suivi des commandes.",
    type: "website",
    url: "/orders",
  },
  twitter: {
    card: "summary",
    title: "Orders",
    description: "Liste et suivi des commandes.",
  },
};

export default function Page() {
  return <WebFeatureRenderer featureId="orders" pageId="index" />;
}
