// Generated by @starter/navigation from packages/features/routes.config.json.
// Do not edit this file directly.
import { NativeFeatureRenderer } from "@starter/ui-native";

export default function Screen() {
  return <NativeFeatureRenderer featureId="settings" />;
}
