// Generated by @starter/navigation from packages/features/src/app.feature.ts.
// Do not edit this file directly.
import { NativeFeatureRenderer } from "@starter/ui-native";

export default function Screen() {
  return <NativeFeatureRenderer featureId="settings" pageId="index" />;
}
