// Generated by @starter/navigation from packages/features/src/app.feature.ts.
// Do not edit this file directly.
import { handleFeatureRequest } from "../../../../../server/feature-backend";

interface RouteContext {
  readonly params: Promise<{ readonly featureId: string; readonly operationId: string }>;
}

async function dispatch(request: Request, context: RouteContext): Promise<Response> {
  return handleFeatureRequest(request, await context.params);
}

export { dispatch as DELETE, dispatch as GET, dispatch as PATCH, dispatch as POST };
