// Generated by @starter/navigation from packages/features/src/app.feature.ts.
// Do not edit this file directly.
import { handleFeatureRequest } from "../../../../../server/feature-backend";

interface RouteContext {
  readonly params: Promise<{ readonly featureId: string; readonly operationId: string }>;
}

export async function POST(request: Request, context: RouteContext): Promise<Response> {
  return handleFeatureRequest(request, await context.params);
}
