// Generated by @starter/navigation from packages/features/src/app.feature.ts.
// Do not edit this file directly.
import { WebFeatureRenderer } from "@starter/ui-web";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Profil",
  description: "Consultation et modification du profil utilisateur.",
  alternates: { canonical: "/profil" },
  robots: { index: false, follow: false },
  openGraph: {
    title: "Profil",
    description: "Consultation et modification du profil utilisateur.",
    type: "website",
    url: "/profil",
  },
  twitter: {
    card: "summary",
    title: "Profil",
    description: "Consultation et modification du profil utilisateur.",
  },
};

export default function Page() {
  return <WebFeatureRenderer featureId="profile" pageId="index" />;
}
