// Generated by @starter/navigation from packages/features/routes.config.json.
// Do not edit this file directly.
import { WebFeatureRenderer } from "@starter/ui-web";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Profil",
  description: "Gestion locale du profil de démonstration.",
  alternates: { canonical: "/profil" },
  robots: { index: false, follow: false },
  openGraph: {
    title: "Profil",
    description: "Gestion locale du profil de démonstration.",
    type: "website",
    url: "/profil",
  },
  twitter: {
    card: "summary",
    title: "Profil",
    description: "Gestion locale du profil de démonstration.",
  },
};

export default function Page() {
  return <WebFeatureRenderer featureId="profile" />;
}
