// Generated by @starter/navigation from packages/features/src/app.feature.ts.
// Do not edit this file directly.
import { WebFeatureRenderer } from "@starter/ui-web";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Customers",
  description: "Répertoire des clients.",
  alternates: { canonical: "/customers" },
  robots: { index: false, follow: false },
  openGraph: {
    title: "Customers",
    description: "Répertoire des clients.",
    type: "website",
    url: "/customers",
  },
  twitter: {
    card: "summary",
    title: "Customers",
    description: "Répertoire des clients.",
  },
};

export default function Page() {
  return <WebFeatureRenderer featureId="customers" pageId="index" />;
}
