// Generated by @starter/navigation from packages/features/routes.config.json.
// Do not edit this file directly.
"use client";

import { WebFeatureRenderer } from "@starter/ui-web";

export default function ErrorPage() {
  return <WebFeatureRenderer featureId="system-error" />;
}
