// Generated by @starter/navigation from packages/features/src/app.feature.ts.
// Do not edit this file directly.
"use client";

import { WebFeatureRenderer } from "@starter/ui-web";

export default function ErrorPage() {
  return <WebFeatureRenderer featureId="system-error" />;
}
