// Generated by @starter/navigation from packages/features/routes.config.json.
// Do not edit this file directly.
import type { MetadataRoute } from "next";

export default function manifest(): MetadataRoute.Manifest {
  return {
    name: "__PROJECT_NAME__",
    short_name: "__PROJECT_NAME__",
    description: "Une logique UI partagée entre le Web et le Mobile.",
    start_url: "/",
    display: "standalone",
  };
}
