// Generated by @starter/navigation from packages/features/src/app.feature.ts.
// Do not edit this file directly.
import type { MetadataRoute } from "next";

export default function manifest(): MetadataRoute.Manifest {
  return {
    name: "__PROJECT_NAME__",
    short_name: "__PROJECT_NAME__",
    description: "Démonstration des fonctionnalités partagées Messanga11.",
    start_url: "/",
    display: "standalone",
  };
}
