// Generated by @starter/navigation from packages/features/src/app.feature.ts.
// Do not edit this file directly.
import { WebFeatureRenderer } from "@starter/ui-web";

export default function SystemPage() {
  return <WebFeatureRenderer featureId="system-not-found" />;
}
