// Generated by @starter/navigation from packages/features/routes.config.json.
// Do not edit this file directly.
import { WebFeatureRenderer } from "@starter/ui-web";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Tableau de bord",
  description: "Tableau de bord de démonstration Messanga11.",
  alternates: { canonical: "/" },
  robots: { index: false, follow: false },
  openGraph: {
    title: "Tableau de bord",
    description: "Tableau de bord de démonstration Messanga11.",
    type: "website",
    url: "/",
  },
  twitter: {
    card: "summary",
    title: "Tableau de bord",
    description: "Tableau de bord de démonstration Messanga11.",
  },
};

export default function Page() {
  return <WebFeatureRenderer featureId="dashboard" />;
}
