// Generated by @starter/navigation from packages/features/routes.config.json.
// Do not edit this file directly.
import { WebFeatureRenderer } from "@starter/ui-web";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "__PROJECT_NAME__",
  description: "Une logique UI partagée entre le Web et le Mobile.",
  alternates: { canonical: "/" },
  robots: { index: true, follow: true },
  openGraph: {
    title: "__PROJECT_NAME__",
    description: "Une logique UI partagée entre le Web et le Mobile.",
    type: "website",
    url: "/",
  },
  twitter: {
    card: "summary",
    title: "__PROJECT_NAME__",
    description: "Une logique UI partagée entre le Web et le Mobile.",
  },
};

export default function Page() {
  return <WebFeatureRenderer featureId="profile" />;
}
