// Generated by @starter/navigation from packages/features/routes.config.json.
// Do not edit this file directly.
import type { MetadataRoute } from "next";
import { getSiteUrl } from "./site-url";

const INDEXED_PATHS = ["/"] as const;

export default function sitemap(): MetadataRoute.Sitemap {
  const siteUrl = getSiteUrl();
  return INDEXED_PATHS.map((path) => ({ url: new URL(path, siteUrl).toString() }));
}
