// Generated by @starter/navigation from packages/features/routes.config.json.
// Do not edit this file directly.
export function getSiteUrl(): URL {
  const url = new URL(process.env.NEXT_PUBLIC_SITE_URL ?? "http://localhost:3000");
  if (url.protocol !== "http:" && url.protocol !== "https:") {
    throw new Error("NEXT_PUBLIC_SITE_URL must use HTTP or HTTPS.");
  }
  return url;
}
