// Generated by @starter/navigation from packages/features/src/app.feature.ts.
// Do not edit this file directly.
import { WebFeatureRenderer } from "@starter/ui-web";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Équipe",
  description: "Gestion des membres, rôles et invitations de l'équipe.",
  alternates: { canonical: "/equipe" },
  robots: { index: false, follow: false },
  openGraph: {
    title: "Équipe",
    description: "Gestion des membres, rôles et invitations de l'équipe.",
    type: "website",
    url: "/equipe",
  },
  twitter: {
    card: "summary",
    title: "Équipe",
    description: "Gestion des membres, rôles et invitations de l'équipe.",
  },
};

export default function Page() {
  return <WebFeatureRenderer featureId="team" pageId="index" />;
}
