// Generated by @starter/navigation from packages/features/routes.config.json.
// Do not edit this file directly.
import { WebFeatureRenderer } from "@starter/ui-web";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Gestion d’équipe",
  description: "Gestion locale d’une équipe de démonstration.",
  alternates: { canonical: "/equipe" },
  robots: { index: false, follow: false },
  openGraph: {
    title: "Gestion d’équipe",
    description: "Gestion locale d’une équipe de démonstration.",
    type: "website",
    url: "/equipe",
  },
  twitter: {
    card: "summary",
    title: "Gestion d’équipe",
    description: "Gestion locale d’une équipe de démonstration.",
  },
};

export default function Page() {
  return <WebFeatureRenderer featureId="team" />;
}
