// Generated by @starter/navigation from packages/features/routes.config.json.
// Do not edit this file directly.
import { WebFeatureRenderer } from "@starter/ui-web";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "FormBuilder complexe",
  description: "Démonstration du FormBuilder partagé Web et Native.",
  alternates: { canonical: "/formulaire" },
  robots: { index: false, follow: false },
  openGraph: {
    title: "FormBuilder complexe",
    description: "Démonstration du FormBuilder partagé Web et Native.",
    type: "website",
    url: "/formulaire",
  },
  twitter: {
    card: "summary",
    title: "FormBuilder complexe",
    description: "Démonstration du FormBuilder partagé Web et Native.",
  },
};

export default function Page() {
  return <WebFeatureRenderer featureId="form-builder" />;
}
