// Generated by @starter/navigation from packages/features/src/app.feature.ts.
// Do not edit this file directly.
import { WebFeatureRenderer } from "@starter/ui-web";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Stores",
  description: "Réseau des points de vente.",
  alternates: { canonical: "/stores" },
  robots: { index: false, follow: false },
  openGraph: {
    title: "Stores",
    description: "Réseau des points de vente.",
    type: "website",
    url: "/stores",
  },
  twitter: {
    card: "summary",
    title: "Stores",
    description: "Réseau des points de vente.",
  },
};

export default function Page() {
  return <WebFeatureRenderer featureId="stores" pageId="index" />;
}
