// Generated by @starter/navigation from packages/features/routes.config.json.
// Do not edit this file directly.
import { WebFeatureRenderer } from "@starter/ui-web";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Authentification",
  description: "Écran local de démonstration de l’authentification.",
  alternates: { canonical: "/authentification" },
  robots: { index: false, follow: false },
  openGraph: {
    title: "Authentification",
    description: "Écran local de démonstration de l’authentification.",
    type: "website",
    url: "/authentification",
  },
  twitter: {
    card: "summary",
    title: "Authentification",
    description: "Écran local de démonstration de l’authentification.",
  },
};

export default function Page() {
  return <WebFeatureRenderer featureId="authentication" />;
}
