// Generated by @starter/navigation from packages/features/src/app.feature.ts.
// Do not edit this file directly.
import { WebFeatureRenderer } from "@starter/ui-web";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Authentification",
  description: "Connexion sécurisée à la démonstration Messanga11.",
  alternates: { canonical: "/authentification" },
  robots: { index: false, follow: false },
  openGraph: {
    title: "Authentification",
    description: "Connexion sécurisée à la démonstration Messanga11.",
    type: "website",
    url: "/authentification",
  },
  twitter: {
    card: "summary",
    title: "Authentification",
    description: "Connexion sécurisée à la démonstration Messanga11.",
  },
};

export default function Page() {
  return <WebFeatureRenderer featureId="authentication" pageId="index" />;
}
