// Generated by @starter/navigation from packages/features/src/app.feature.ts.
// Do not edit this file directly.
import { WebFeatureRenderer } from "@starter/ui-web";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Categories",
  description: "Organisation des catégories produits.",
  alternates: { canonical: "/categories" },
  robots: { index: false, follow: false },
  openGraph: {
    title: "Categories",
    description: "Organisation des catégories produits.",
    type: "website",
    url: "/categories",
  },
  twitter: {
    card: "summary",
    title: "Categories",
    description: "Organisation des catégories produits.",
  },
};

export default function Page() {
  return <WebFeatureRenderer featureId="categories" pageId="index" />;
}
