// Generated by @starter/navigation from packages/features/src/app.feature.ts.
// Do not edit this file directly.
import { WebFeatureRenderer } from "@starter/ui-web";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Notifications",
  description: "Centre de notifications et préférences de communication.",
  alternates: { canonical: "/notifications" },
  robots: { index: false, follow: false },
  openGraph: {
    title: "Notifications",
    description: "Centre de notifications et préférences de communication.",
    type: "website",
    url: "/notifications",
  },
  twitter: {
    card: "summary",
    title: "Notifications",
    description: "Centre de notifications et préférences de communication.",
  },
};

export default function Page() {
  return <WebFeatureRenderer featureId="notifications" pageId="index" />;
}
