import { randomUUID } from "node:crypto";
import {
  access,
  mkdir,
  readFile,
  rename,
  stat,
  unlink,
  writeFile,
} from "node:fs/promises";
import { dirname, relative, resolve, sep } from "node:path";
import process from "node:process";
import { fileURLToPath, pathToFileURL } from "node:url";
import { compileFeatureCatalog } from "@messanga11/core/features";

const GENERATED_HEADER =
  "// Generated by @starter/navigation from packages/features/src/app.feature.ts.\n// Do not edit this file directly.\n";
const scriptDirectory = dirname(fileURLToPath(import.meta.url));
export const workspaceRoot = resolve(scriptDirectory, "../../..");
export const routesConfigPath = resolve(
  workspaceRoot,
  "packages/features/src/app.feature.ts",
);
const manifestPath = resolve(workspaceRoot, "packages/navigation/generated-files.json");
export async function generateRoutes(options = {}) {
  const config = await loadGeneratorConfig();
  const expected = buildGeneratedFiles(config);
  const previous = await readGeneratedManifest();

  if (options.check) {
    await assertGeneratedFilesCurrent(expected, previous);
    return expected;
  }

  for (const stalePath of previous) {
    if (!expected.has(stalePath)) {
      await removeGeneratedFile(stalePath);
    }
  }
  for (const [relativePath, contents] of expected) {
    await writeGeneratedFile(relativePath, contents);
  }
  await writeAtomic(manifestPath, serializeManifest(expected));
  return expected;
}

async function loadGeneratorConfig() {
  const modifiedAt = (await stat(routesConfigPath)).mtimeMs;
  const module = await import(
    `${pathToFileURL(routesConfigPath).href}?v=${modifiedAt}`
  );
  const compiled = compileFeatureCatalog(module.APP_FEATURE_CATALOG);
  const routes = [];
  for (const feature of compiled.definition.features) {
    for (const page of feature.pages) {
      routes.push({
        featureId: feature.id,
        id: `${feature.id}.${page.id}`,
        ...(page.routes.mobile ? { mobile: page.routes.mobile } : {}),
        pageId: page.id,
        ...(page.routes.web
          ? {
              web: {
                description: page.routes.web.seo.description,
                index: page.routes.web.seo.index,
                path: page.routes.web.path,
                title: page.routes.web.seo.title,
              },
            }
          : {}),
      });
    }
  }
  return {
    app: {
      description: compiled.definition.application.description,
      language: compiled.definition.application.defaultLocale,
      name: compiled.definition.application.name,
      shortName: compiled.definition.application.shortName,
    },
    routes,
  };
}

function buildGeneratedFiles(config) {
  const files = new Map();
  for (const route of config.routes) {
    if (route.web) files.set(webRouteFile(route.web.path), renderWebRoute(route));
    if (route.mobile)
      files.set(mobileRouteFile(route.mobile.path), renderMobileRoute(route));
  }
  files.set("apps/web/src/app/not-found.tsx", renderWebSystem("system-not-found"));
  files.set("apps/web/src/app/loading.tsx", renderWebSystem("system-loading"));
  files.set("apps/web/src/app/error.tsx", renderWebError());
  files.set("apps/web/src/app/robots.ts", renderRobots());
  files.set("apps/web/src/app/sitemap.ts", renderSitemap(config));
  files.set("apps/web/src/app/site-url.ts", renderSiteUrl());
  files.set("apps/web/src/app/manifest.ts", renderManifest(config));
  files.set(
    "apps/web/src/app/api/features/[featureId]/[operationId]/route.ts",
    renderFeatureApiRoute(),
  );
  files.set("apps/mobile/app/+not-found.tsx", renderMobileSystem());
  return new Map(
    [...files.entries()].sort(([left], [right]) => left.localeCompare(right)),
  );
}

function renderWebRoute(route) {
  const title = JSON.stringify(route.web.title);
  const description = JSON.stringify(route.web.description);
  const path = JSON.stringify(route.web.path);
  return `${GENERATED_HEADER}import { WebFeatureRenderer } from "@starter/ui-web";\nimport type { Metadata } from "next";\n\nexport const metadata: Metadata = {\n  title: ${title},\n  description: ${description},\n  alternates: { canonical: ${path} },\n  robots: { index: ${route.web.index}, follow: ${route.web.index} },\n  openGraph: {\n    title: ${title},\n    description: ${description},\n    type: "website",\n    url: ${path},\n  },\n  twitter: {\n    card: "summary",\n    title: ${title},\n    description: ${description},\n  },\n};\n\nexport default function Page() {\n  return <WebFeatureRenderer featureId=${JSON.stringify(route.featureId)} pageId=${JSON.stringify(route.pageId)} />;\n}\n`;
}

function renderMobileRoute(route) {
  return `${GENERATED_HEADER}import { NativeFeatureRenderer } from "@starter/ui-native";\n\nexport default function Screen() {\n  return <NativeFeatureRenderer featureId=${JSON.stringify(route.featureId)} pageId=${JSON.stringify(route.pageId)} />;\n}\n`;
}

function renderWebSystem(featureId) {
  return `${GENERATED_HEADER}import { WebFeatureRenderer } from "@starter/ui-web";\n\nexport default function SystemPage() {\n  return <WebFeatureRenderer featureId=${JSON.stringify(featureId)} />;\n}\n`;
}

function renderWebError() {
  return `${GENERATED_HEADER}"use client";\n\nimport { WebFeatureRenderer } from "@starter/ui-web";\n\nexport default function ErrorPage() {\n  return <WebFeatureRenderer featureId="system-error" />;\n}\n`;
}

function renderMobileSystem() {
  return `${GENERATED_HEADER}import { NativeFeatureRenderer } from "@starter/ui-native";\n\nexport default function NotFoundScreen() {\n  return <NativeFeatureRenderer featureId="system-not-found" />;\n}\n`;
}

function renderFeatureApiRoute() {
  return `${GENERATED_HEADER}import { handleFeatureRequest } from "../../../../../server/feature-backend";\n\ninterface RouteContext {\n  readonly params: Promise<{ readonly featureId: string; readonly operationId: string }>;\n}\n\nasync function dispatch(request: Request, context: RouteContext): Promise<Response> {\n  return handleFeatureRequest(request, await context.params);\n}\n\nexport { dispatch as DELETE, dispatch as GET, dispatch as PATCH, dispatch as POST };\n`;
}

function renderRobots() {
  return `${GENERATED_HEADER}import type { MetadataRoute } from "next";\nimport { getSiteUrl } from "./site-url";\n\nexport default function robots(): MetadataRoute.Robots {\n  return {\n    rules: { userAgent: "*", allow: "/" },\n    sitemap: new URL("/sitemap.xml", getSiteUrl()).toString(),\n  };\n}\n`;
}

function renderSitemap(config) {
  const indexedPaths = config.routes
    .filter((route) => route.web?.index)
    .map((route) => route.web.path);
  return `${GENERATED_HEADER}import type { MetadataRoute } from "next";\nimport { getSiteUrl } from "./site-url";\n\nconst INDEXED_PATHS = ${JSON.stringify(indexedPaths)} as const;\n\nexport default function sitemap(): MetadataRoute.Sitemap {\n  const siteUrl = getSiteUrl();\n  return INDEXED_PATHS.map((path) => ({ url: new URL(path, siteUrl).toString() }));\n}\n`;
}

function renderSiteUrl() {
  return `${GENERATED_HEADER}export function getSiteUrl(): URL {\n  const url = new URL(process.env.NEXT_PUBLIC_SITE_URL ?? "http://localhost:3000");\n  if (url.protocol !== "http:" && url.protocol !== "https:") {\n    throw new Error("NEXT_PUBLIC_SITE_URL must use HTTP or HTTPS.");\n  }\n  return url;\n}\n`;
}

function renderManifest(config) {
  return `${GENERATED_HEADER}import type { MetadataRoute } from "next";\n\nexport default function manifest(): MetadataRoute.Manifest {\n  return {\n    name: ${JSON.stringify(config.app.name)},\n    short_name: ${JSON.stringify(config.app.shortName)},\n    description: ${JSON.stringify(config.app.description)},\n    start_url: "/",\n    display: "standalone",\n  };\n}\n`;
}

function webRouteFile(path) {
  return path === "/"
    ? "apps/web/src/app/page.tsx"
    : `apps/web/src/app${path}/page.tsx`;
}

function mobileRouteFile(path) {
  return path === "/" ? "apps/mobile/app/index.tsx" : `apps/mobile/app${path}.tsx`;
}

async function assertGeneratedFilesCurrent(expected, previous) {
  const failures = [];
  if (JSON.stringify([...previous].sort()) !== JSON.stringify([...expected.keys()])) {
    failures.push("generated-files.json is stale");
  }
  for (const [relativePath, contents] of expected) {
    const current = await readOptional(resolveSafeGeneratedPath(relativePath));
    if (current !== contents) {
      failures.push(relativePath);
    }
  }
  if (failures.length > 0) {
    throw new Error(
      `Generated routes are stale: ${failures.join(", ")}. Run npm run routes:generate.`,
    );
  }
}

async function writeGeneratedFile(relativePath, contents) {
  const target = resolveSafeGeneratedPath(relativePath);
  const current = await readOptional(target);
  if (current !== undefined && !isGenerated(current)) {
    throw new Error(`Refusing to overwrite non-generated file: ${relativePath}`);
  }
  await mkdir(dirname(target), { recursive: true });
  await writeAtomic(target, contents);
}

async function writeAtomic(target, contents) {
  const temporaryPath = `${target}.${process.pid}.${randomUUID()}.tmp`;
  await writeFile(temporaryPath, contents, "utf8");
  await rename(temporaryPath, target);
}

async function removeGeneratedFile(relativePath) {
  const target = resolveSafeGeneratedPath(relativePath);
  const current = await readOptional(target);
  if (current === undefined) return;
  if (!isGenerated(current)) {
    throw new Error(`Refusing to remove non-generated file: ${relativePath}`);
  }
  await unlink(target);
}

function isGenerated(contents) {
  return contents.startsWith(GENERATED_HEADER);
}

function resolveSafeGeneratedPath(relativePath) {
  const target = resolve(workspaceRoot, relativePath);
  const allowedRoots = [
    resolve(workspaceRoot, "apps/web/src/app"),
    resolve(workspaceRoot, "apps/mobile/app"),
  ];
  if (!allowedRoots.some((root) => isWithin(root, target))) {
    throw new Error(
      `Generated path escapes an application route root: ${relativePath}`,
    );
  }
  return target;
}

function isWithin(root, target) {
  const path = relative(root, target);
  return path === "" || (!path.startsWith(`..${sep}`) && path !== "..");
}

async function readGeneratedManifest() {
  const value = JSON.parse(await readFile(manifestPath, "utf8"));
  if (
    !Array.isArray(value.files) ||
    !value.files.every((item) => typeof item === "string")
  ) {
    throw new Error("generated-files.json is invalid.");
  }
  for (const path of value.files) resolveSafeGeneratedPath(path);
  return new Set(value.files);
}

function serializeManifest(files) {
  return `${JSON.stringify({ files: [...files.keys()] }, null, 2)}\n`;
}

async function readOptional(path) {
  try {
    await access(path);
    return await readFile(path, "utf8");
  } catch (error) {
    if (
      error &&
      typeof error === "object" &&
      "code" in error &&
      error.code === "ENOENT"
    ) {
      return undefined;
    }
    throw error;
  }
}

const invokedPath = process.argv[1] ? pathToFileURL(resolve(process.argv[1])).href : "";
if (import.meta.url === invokedPath) {
  await generateRoutes({ check: process.argv.includes("--check") });
}
