import { randomUUID } from "node:crypto";
import { access, mkdir, readFile, rename, unlink, writeFile } from "node:fs/promises";
import { dirname, relative, resolve, sep } from "node:path";
import process from "node:process";
import { fileURLToPath, pathToFileURL } from "node:url";

const GENERATED_HEADER =
  "// Generated by @starter/navigation from packages/features/routes.config.json.\n// Do not edit this file directly.\n";
const scriptDirectory = dirname(fileURLToPath(import.meta.url));
export const workspaceRoot = resolve(scriptDirectory, "../../..");
export const routesConfigPath = resolve(
  workspaceRoot,
  "packages/features/routes.config.json",
);
const manifestPath = resolve(workspaceRoot, "packages/navigation/generated-files.json");
const routeIdPattern = /^[a-z][a-z0-9-]{0,49}$/;
const languagePattern = /^[a-z]{2}(?:-[A-Z]{2})?$/;
const pathSegmentPattern = /^[a-z0-9-]+$/;

export function validateRoutesConfig(value) {
  assertRecord(value, "Route configuration");
  assertKeys(value, ["app", "routes"], "Route configuration");
  assertRecord(value.app, "app");
  assertKeys(value.app, ["description", "language", "name", "shortName"], "app");
  assertString(value.app.name, "app.name", 80);
  assertString(value.app.shortName, "app.shortName", 30);
  assertString(value.app.description, "app.description", 160);
  assertString(value.app.language, "app.language", 10);
  if (!languagePattern.test(value.app.language)) {
    throw new Error("app.language must be a language tag such as fr or fr-FR.");
  }
  if (!Array.isArray(value.routes) || value.routes.length === 0) {
    throw new Error("routes must contain at least one declared route.");
  }

  const ids = new Set();
  const webPaths = new Set();
  const mobilePaths = new Set();
  for (const [index, route] of value.routes.entries()) {
    validateRoute(route, index);
    addUnique(ids, route.id, `route id ${route.id}`);
    addUnique(webPaths, route.web.path, `Web path ${route.web.path}`);
    addUnique(mobilePaths, route.mobile.path, `Mobile path ${route.mobile.path}`);
  }
  return value;
}

export async function generateRoutes(options = {}) {
  const config = validateRoutesConfig(
    JSON.parse(await readFile(routesConfigPath, "utf8")),
  );
  const expected = buildGeneratedFiles(config);
  const previous = await readGeneratedManifest();

  if (options.check) {
    await assertGeneratedFilesCurrent(expected, previous);
    return expected;
  }

  for (const stalePath of previous) {
    if (!expected.has(stalePath)) {
      await removeGeneratedFile(stalePath);
    }
  }
  for (const [relativePath, contents] of expected) {
    await writeGeneratedFile(relativePath, contents);
  }
  await writeAtomic(manifestPath, serializeManifest(expected));
  return expected;
}

function validateRoute(route, index) {
  const label = `routes[${index}]`;
  assertRecord(route, label);
  assertKeys(route, ["featureId", "id", "mobile", "web"], label);
  assertIdentifier(route.id, `${label}.id`);
  assertIdentifier(route.featureId, `${label}.featureId`);
  assertRecord(route.web, `${label}.web`);
  assertKeys(route.web, ["description", "index", "path", "title"], `${label}.web`);
  assertRoutePath(route.web.path, `${label}.web.path`);
  assertString(route.web.title, `${label}.web.title`, 80);
  assertString(route.web.description, `${label}.web.description`, 160);
  if (typeof route.web.index !== "boolean") {
    throw new Error(`${label}.web.index must be a boolean.`);
  }
  assertRecord(route.mobile, `${label}.mobile`);
  assertKeys(route.mobile, ["path"], `${label}.mobile`);
  assertRoutePath(route.mobile.path, `${label}.mobile.path`);
}

function buildGeneratedFiles(config) {
  const files = new Map();
  for (const route of config.routes) {
    files.set(webRouteFile(route.web.path), renderWebRoute(route));
    files.set(mobileRouteFile(route.mobile.path), renderMobileRoute(route));
  }
  files.set("apps/web/src/app/not-found.tsx", renderWebSystem("system-not-found"));
  files.set("apps/web/src/app/loading.tsx", renderWebSystem("system-loading"));
  files.set("apps/web/src/app/error.tsx", renderWebError());
  files.set("apps/web/src/app/robots.ts", renderRobots());
  files.set("apps/web/src/app/sitemap.ts", renderSitemap(config));
  files.set("apps/web/src/app/site-url.ts", renderSiteUrl());
  files.set("apps/web/src/app/manifest.ts", renderManifest(config));
  files.set("apps/mobile/app/+not-found.tsx", renderMobileSystem());
  return new Map(
    [...files.entries()].sort(([left], [right]) => left.localeCompare(right)),
  );
}

function renderWebRoute(route) {
  const title = JSON.stringify(route.web.title);
  const description = JSON.stringify(route.web.description);
  const path = JSON.stringify(route.web.path);
  return `${GENERATED_HEADER}import { WebFeatureRenderer } from "@starter/ui-web";\nimport type { Metadata } from "next";\n\nexport const metadata: Metadata = {\n  title: ${title},\n  description: ${description},\n  alternates: { canonical: ${path} },\n  robots: { index: ${route.web.index}, follow: ${route.web.index} },\n  openGraph: {\n    title: ${title},\n    description: ${description},\n    type: "website",\n    url: ${path},\n  },\n  twitter: {\n    card: "summary",\n    title: ${title},\n    description: ${description},\n  },\n};\n\nexport default function Page() {\n  return <WebFeatureRenderer featureId=${JSON.stringify(route.featureId)} />;\n}\n`;
}

function renderMobileRoute(route) {
  return `${GENERATED_HEADER}import { NativeFeatureRenderer } from "@starter/ui-native";\n\nexport default function Screen() {\n  return <NativeFeatureRenderer featureId=${JSON.stringify(route.featureId)} />;\n}\n`;
}

function renderWebSystem(featureId) {
  return `${GENERATED_HEADER}import { WebFeatureRenderer } from "@starter/ui-web";\n\nexport default function SystemPage() {\n  return <WebFeatureRenderer featureId=${JSON.stringify(featureId)} />;\n}\n`;
}

function renderWebError() {
  return `${GENERATED_HEADER}"use client";\n\nimport { WebFeatureRenderer } from "@starter/ui-web";\n\nexport default function ErrorPage() {\n  return <WebFeatureRenderer featureId="system-error" />;\n}\n`;
}

function renderMobileSystem() {
  return `${GENERATED_HEADER}import { NativeFeatureRenderer } from "@starter/ui-native";\n\nexport default function NotFoundScreen() {\n  return <NativeFeatureRenderer featureId="system-not-found" />;\n}\n`;
}

function renderRobots() {
  return `${GENERATED_HEADER}import type { MetadataRoute } from "next";\nimport { getSiteUrl } from "./site-url";\n\nexport default function robots(): MetadataRoute.Robots {\n  return {\n    rules: { userAgent: "*", allow: "/" },\n    sitemap: new URL("/sitemap.xml", getSiteUrl()).toString(),\n  };\n}\n`;
}

function renderSitemap(config) {
  const indexedPaths = config.routes
    .filter((route) => route.web.index)
    .map((route) => route.web.path);
  return `${GENERATED_HEADER}import type { MetadataRoute } from "next";\nimport { getSiteUrl } from "./site-url";\n\nconst INDEXED_PATHS = ${JSON.stringify(indexedPaths)} as const;\n\nexport default function sitemap(): MetadataRoute.Sitemap {\n  const siteUrl = getSiteUrl();\n  return INDEXED_PATHS.map((path) => ({ url: new URL(path, siteUrl).toString() }));\n}\n`;
}

function renderSiteUrl() {
  return `${GENERATED_HEADER}export function getSiteUrl(): URL {\n  const url = new URL(process.env.NEXT_PUBLIC_SITE_URL ?? "http://localhost:3000");\n  if (url.protocol !== "http:" && url.protocol !== "https:") {\n    throw new Error("NEXT_PUBLIC_SITE_URL must use HTTP or HTTPS.");\n  }\n  return url;\n}\n`;
}

function renderManifest(config) {
  return `${GENERATED_HEADER}import type { MetadataRoute } from "next";\n\nexport default function manifest(): MetadataRoute.Manifest {\n  return {\n    name: ${JSON.stringify(config.app.name)},\n    short_name: ${JSON.stringify(config.app.shortName)},\n    description: ${JSON.stringify(config.app.description)},\n    start_url: "/",\n    display: "standalone",\n  };\n}\n`;
}

function webRouteFile(path) {
  return path === "/"
    ? "apps/web/src/app/page.tsx"
    : `apps/web/src/app${path}/page.tsx`;
}

function mobileRouteFile(path) {
  return path === "/" ? "apps/mobile/app/index.tsx" : `apps/mobile/app${path}.tsx`;
}

async function assertGeneratedFilesCurrent(expected, previous) {
  const failures = [];
  if (JSON.stringify([...previous].sort()) !== JSON.stringify([...expected.keys()])) {
    failures.push("generated-files.json is stale");
  }
  for (const [relativePath, contents] of expected) {
    const current = await readOptional(resolveSafeGeneratedPath(relativePath));
    if (current !== contents) {
      failures.push(relativePath);
    }
  }
  if (failures.length > 0) {
    throw new Error(
      `Generated routes are stale: ${failures.join(", ")}. Run npm run routes:generate.`,
    );
  }
}

async function writeGeneratedFile(relativePath, contents) {
  const target = resolveSafeGeneratedPath(relativePath);
  const current = await readOptional(target);
  if (current !== undefined && !current.startsWith(GENERATED_HEADER)) {
    throw new Error(`Refusing to overwrite non-generated file: ${relativePath}`);
  }
  await mkdir(dirname(target), { recursive: true });
  await writeAtomic(target, contents);
}

async function writeAtomic(target, contents) {
  const temporaryPath = `${target}.${process.pid}.${randomUUID()}.tmp`;
  await writeFile(temporaryPath, contents, "utf8");
  await rename(temporaryPath, target);
}

async function removeGeneratedFile(relativePath) {
  const target = resolveSafeGeneratedPath(relativePath);
  const current = await readOptional(target);
  if (current === undefined) return;
  if (!current.startsWith(GENERATED_HEADER)) {
    throw new Error(`Refusing to remove non-generated file: ${relativePath}`);
  }
  await unlink(target);
}

function resolveSafeGeneratedPath(relativePath) {
  const target = resolve(workspaceRoot, relativePath);
  const allowedRoots = [
    resolve(workspaceRoot, "apps/web/src/app"),
    resolve(workspaceRoot, "apps/mobile/app"),
  ];
  if (!allowedRoots.some((root) => isWithin(root, target))) {
    throw new Error(
      `Generated path escapes an application route root: ${relativePath}`,
    );
  }
  return target;
}

function isWithin(root, target) {
  const path = relative(root, target);
  return path === "" || (!path.startsWith(`..${sep}`) && path !== "..");
}

async function readGeneratedManifest() {
  const value = JSON.parse(await readFile(manifestPath, "utf8"));
  if (
    !Array.isArray(value.files) ||
    !value.files.every((item) => typeof item === "string")
  ) {
    throw new Error("generated-files.json is invalid.");
  }
  for (const path of value.files) resolveSafeGeneratedPath(path);
  return new Set(value.files);
}

function serializeManifest(files) {
  return `${JSON.stringify({ files: [...files.keys()] }, null, 2)}\n`;
}

async function readOptional(path) {
  try {
    await access(path);
    return await readFile(path, "utf8");
  } catch (error) {
    if (
      error &&
      typeof error === "object" &&
      "code" in error &&
      error.code === "ENOENT"
    ) {
      return undefined;
    }
    throw error;
  }
}

function assertRecord(value, label) {
  if (value === null || typeof value !== "object" || Array.isArray(value)) {
    throw new Error(`${label} must be an object.`);
  }
}

function assertKeys(value, allowedKeys, label) {
  const allowed = new Set(allowedKeys);
  const unknown = Object.keys(value).filter((key) => !allowed.has(key));
  if (unknown.length > 0) {
    throw new Error(`${label} contains unknown fields: ${unknown.join(", ")}.`);
  }
}

function assertString(value, label, maxLength) {
  if (typeof value !== "string" || value.length === 0 || value.length > maxLength) {
    throw new Error(
      `${label} must be a non-empty string up to ${maxLength} characters.`,
    );
  }
}

function assertIdentifier(value, label) {
  if (typeof value !== "string" || !routeIdPattern.test(value)) {
    throw new Error(`${label} must use lowercase letters, numbers and hyphens.`);
  }
}

function assertRoutePath(value, label) {
  if (typeof value !== "string" || value.length > 200 || !value.startsWith("/")) {
    throw new Error(`${label} must be an absolute route path.`);
  }
  if (
    value !== "/" &&
    value
      .split("/")
      .slice(1)
      .some((part) => !pathSegmentPattern.test(part))
  ) {
    throw new Error(`${label} contains an unsafe or unsupported segment.`);
  }
}

function addUnique(values, value, label) {
  if (values.has(value)) throw new Error(`Duplicate ${label}.`);
  values.add(value);
}

const invokedPath = process.argv[1] ? pathToFileURL(resolve(process.argv[1])).href : "";
if (import.meta.url === invokedPath) {
  await generateRoutes({ check: process.argv.includes("--check") });
}
