// Generated by @starter/navigation from packages/features/src/app.feature.ts.
// Do not edit this file directly.
import { WebFeatureRenderer } from "@starter/ui-web";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Products",
  description: "Catalogue des produits.",
  alternates: { canonical: "/products" },
  robots: { index: false, follow: false },
  openGraph: {
    title: "Products",
    description: "Catalogue des produits.",
    type: "website",
    url: "/products",
  },
  twitter: {
    card: "summary",
    title: "Products",
    description: "Catalogue des produits.",
  },
};

export default function Page() {
  return <WebFeatureRenderer featureId="products" pageId="index" />;
}
