// Generated by @starter/navigation from packages/features/src/app.feature.ts.
// Do not edit this file directly.
import { WebFeatureRenderer } from "@starter/ui-web";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Couriers",
  description: "Disponibilité et activité des coursiers.",
  alternates: { canonical: "/couriers" },
  robots: { index: false, follow: false },
  openGraph: {
    title: "Couriers",
    description: "Disponibilité et activité des coursiers.",
    type: "website",
    url: "/couriers",
  },
  twitter: {
    card: "summary",
    title: "Couriers",
    description: "Disponibilité et activité des coursiers.",
  },
};

export default function Page() {
  return <WebFeatureRenderer featureId="couriers" pageId="index" />;
}
