// Generated by @starter/navigation from packages/features/src/app.feature.ts.
// Do not edit this file directly.
import { WebFeatureRenderer } from "@starter/ui-web";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Mini générateur de facture",
  description: "Créez et enregistrez une facture de démonstration.",
  alternates: { canonical: "/factures" },
  robots: { index: false, follow: false },
  openGraph: {
    title: "Mini générateur de facture",
    description: "Créez et enregistrez une facture de démonstration.",
    type: "website",
    url: "/factures",
  },
  twitter: {
    card: "summary",
    title: "Mini générateur de facture",
    description: "Créez et enregistrez une facture de démonstration.",
  },
};

export default function Page() {
  return <WebFeatureRenderer featureId="invoice" pageId="index" />;
}
